version: "3.8"

services:
  mmdetection:
    container_name: mmdetection
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PYTORCH: "1.9.0"
        CUDA: "11.1"
        CUDNN: "8"
    entrypoint: ["/bin/bash"]
    volumes:
      - ./mmdetection:/mmdetection
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
